spring:
  application:
    name: meubolso

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:meubolso}
    username: ${DB_USER:meubolso}
    password: ${DB_PASSWORD:meubolso}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: ${SERVER_PORT:4444}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

app:
  security:
    jwt:
      secret: ${JWT_SECRET:change-me-in-env-change-me-in-env-123456}
      access-ttl-min: ${JWT_ACCESS_TTL_MIN:15}
      refresh-ttl-days: ${JWT_REFRESH_TTL_DAYS:7}

springdoc:
  swagger-ui:
    persist-authorization: true
